INSERT INTO regiones (id, nombre) VALUES (1, 'Sudamérica');
INSERT INTO regiones (id, nombre) VALUES (2, 'Centroamérica');
INSERT INTO regiones (id, nombre) VALUES (3, 'Norteamérica');
INSERT INTO regiones (id, nombre) VALUES (4, 'Europa');
INSERT INTO regiones (id, nombre) VALUES (5, 'Asia');
INSERT INTO regiones (id, nombre) VALUES (6, 'África');
INSERT INTO regiones (id, nombre) VALUES (7, 'Oceanía');
INSERT INTO regiones (id, nombre) VALUES (8, 'Antártida');

INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Rubén', 'Ortega', 'ruben@correo.com', '2010-11-26', 3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Lupita', 'García', 'lupita@correo.com', '2011-02-24', 3);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Pedro', 'Miranda', 'pedro@correo.com', '2020-09-11', 4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Martina', 'Jiménez', 'martina@correo.com', '2005-07-07', 1);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Luis', 'Martinez', 'luis@correo.com', '2015-09-22', 2);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Maria', 'Caballero', 'maria@correo.com', '2013-08-10', 4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Yolanda', 'Esquivel', 'yolanda@correo.com', '2014-12-04', 6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('José', 'Gonzalez', 'jose@correo.com', '2018-06-24', 7);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Carmen', 'Sánchez', 'carmen@correo.com', '2008-05-16', 8);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Eva', 'Losada', 'eva@correo.com', '2017-03-13', 6);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Jesús', 'Del Moral', 'jesus@correo.com', '2016-02-07', 4);
INSERT INTO clientes (nombre, apellido, email, create_at, region_id) VALUES ('Antonio', 'Antúnez', 'antonio@correo.com', '2014-01-12', 6);